### ISSUE TITLE
Minor documentation

### ISSUE THREAD

**Issue by ajshajib** [sibirrer/hierArc#15]
I don't really understand what is being done here. I think, it would be helpful to add a little more description or some reference in the comment line.

https://github.com/sibirrer/hierArc/blob/b4771d98da5c7e3aab937fe0bbe1714100e3abbc/hierarc/Likelihood/SneLikelihood/sne_likelihood.py#L103

**Comment by sibirrer** [comment]
'dmb' is the column in the Pantheon sample that contains the intrinsic variance of the SNe population at a given redshift, while the covariance matrix error does only contain measurement errors. This is the mag_var part. The second part is dealing with peculiar velocities to add an error term related to the uncertainty in the actual redshift related to the background metric. This second term is minor.

I hope I am right with this assessment. Original source for this code is here: https://github.com/CobayaSampler/cobaya/blob/112da1dd55b33816441f62b4a808737d220ed8db/cobaya/likelihoods/base_classes/sn.py#L254
