### ISSUE TITLE
Codecov upload token needs to be provided

### ISSUE THREAD

**Issue by ajshajib** [sibirrer/hierArc#37]
@sibirrer, the coverage testing is broken now since Codecov requires the upload token to be added to the `codecov.yml` file. Please go to the Codecov website to find the repository token for this repo and add it to the above-mentioned line.

**Comment by sibirrer** [comment]
Just done. Thank you @ajshajib !

**Comment by ajshajib** [comment]
Thanks, @sibirrer.

This is done with a81a094.
